package net.minestom.server.item.enchant;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface Enchantments {
    Key DEPTH_STRIDER = Key.key("minecraft:depth_strider");

    Key VANISHING_CURSE = Key.key("minecraft:vanishing_curse");

    Key EFFICIENCY = Key.key("minecraft:efficiency");

    Key IMPALING = Key.key("minecraft:impaling");

    Key WIND_BURST = Key.key("minecraft:wind_burst");

    Key BANE_OF_ARTHROPODS = Key.key("minecraft:bane_of_arthropods");

    Key BINDING_CURSE = Key.key("minecraft:binding_curse");

    Key PUNCH = Key.key("minecraft:punch");

    Key FLAME = Key.key("minecraft:flame");

    Key RIPTIDE = Key.key("minecraft:riptide");

    Key BLAST_PROTECTION = Key.key("minecraft:blast_protection");

    Key FROST_WALKER = Key.key("minecraft:frost_walker");

    Key PROTECTION = Key.key("minecraft:protection");

    Key FIRE_ASPECT = Key.key("minecraft:fire_aspect");

    Key LOYALTY = Key.key("minecraft:loyalty");

    Key SWEEPING_EDGE = Key.key("minecraft:sweeping_edge");

    Key FIRE_PROTECTION = Key.key("minecraft:fire_protection");

    Key QUICK_CHARGE = Key.key("minecraft:quick_charge");

    Key RESPIRATION = Key.key("minecraft:respiration");

    Key LUCK_OF_THE_SEA = Key.key("minecraft:luck_of_the_sea");

    Key SOUL_SPEED = Key.key("minecraft:soul_speed");

    Key DENSITY = Key.key("minecraft:density");

    Key POWER = Key.key("minecraft:power");

    Key SILK_TOUCH = Key.key("minecraft:silk_touch");

    Key CHANNELING = Key.key("minecraft:channeling");

    Key FORTUNE = Key.key("minecraft:fortune");

    Key LOOTING = Key.key("minecraft:looting");

    Key BREACH = Key.key("minecraft:breach");

    Key PIERCING = Key.key("minecraft:piercing");

    Key MENDING = Key.key("minecraft:mending");

    Key FEATHER_FALLING = Key.key("minecraft:feather_falling");

    Key SHARPNESS = Key.key("minecraft:sharpness");

    Key KNOCKBACK = Key.key("minecraft:knockback");

    Key SMITE = Key.key("minecraft:smite");

    Key INFINITY = Key.key("minecraft:infinity");

    Key PROJECTILE_PROTECTION = Key.key("minecraft:projectile_protection");

    Key THORNS = Key.key("minecraft:thorns");

    Key AQUA_AFFINITY = Key.key("minecraft:aqua_affinity");

    Key LURE = Key.key("minecraft:lure");

    Key MULTISHOT = Key.key("minecraft:multishot");

    Key SWIFT_SNEAK = Key.key("minecraft:swift_sneak");

    Key UNBREAKING = Key.key("minecraft:unbreaking");
}
