package net.minestom.server.message;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface ChatTypes {
    Key EMOTE_COMMAND = Key.key("minecraft:emote_command");

    Key TEAM_MSG_COMMAND_INCOMING = Key.key("minecraft:team_msg_command_incoming");

    Key TEAM_MSG_COMMAND_OUTGOING = Key.key("minecraft:team_msg_command_outgoing");

    Key CHAT = Key.key("minecraft:chat");

    Key MSG_COMMAND_INCOMING = Key.key("minecraft:msg_command_incoming");

    Key MSG_COMMAND_OUTGOING = Key.key("minecraft:msg_command_outgoing");

    Key SAY_COMMAND = Key.key("minecraft:say_command");
}
