package net.minestom.server.gametag;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface BlockTags {
    Tag SNOW = BlockTag.get("minecraft:snow");

    Tag CHERRY_LOGS = BlockTag.get("minecraft:cherry_logs");

    Tag FIRE = BlockTag.get("minecraft:fire");

    Tag WOODEN_SLABS = BlockTag.get("minecraft:wooden_slabs");

    Tag PLANKS = BlockTag.get("minecraft:planks");

    Tag CONCRETE_POWDER = BlockTag.get("minecraft:concrete_powder");

    Tag BUTTONS = BlockTag.get("minecraft:buttons");

    Tag LUSH_GROUND_REPLACEABLE = BlockTag.get("minecraft:lush_ground_replaceable");

    Tag LAVA_POOL_STONE_CANNOT_REPLACE = BlockTag.get("minecraft:lava_pool_stone_cannot_replace");

    Tag RABBITS_SPAWNABLE_ON = BlockTag.get("minecraft:rabbits_spawnable_on");

    Tag SLABS = BlockTag.get("minecraft:slabs");

    Tag SPRUCE_LOGS = BlockTag.get("minecraft:spruce_logs");

    Tag CRYSTAL_SOUND_BLOCKS = BlockTag.get("minecraft:crystal_sound_blocks");

    Tag WALL_HANGING_SIGNS = BlockTag.get("minecraft:wall_hanging_signs");

    Tag COPPER_ORES = BlockTag.get("minecraft:copper_ores");

    Tag DAMPENS_VIBRATIONS = BlockTag.get("minecraft:dampens_vibrations");

    Tag MINEABLE_SHOVEL = BlockTag.get("minecraft:mineable/shovel");

    Tag MINEABLE_HOE = BlockTag.get("minecraft:mineable/hoe");

    Tag MINEABLE_AXE = BlockTag.get("minecraft:mineable/axe");

    Tag MINEABLE_PICKAXE = BlockTag.get("minecraft:mineable/pickaxe");

    Tag CORALS = BlockTag.get("minecraft:corals");

    Tag CAMPFIRES = BlockTag.get("minecraft:campfires");

    Tag DEAD_BUSH_MAY_PLACE_ON = BlockTag.get("minecraft:dead_bush_may_place_on");

    Tag REPLACEABLE_BY_TREES = BlockTag.get("minecraft:replaceable_by_trees");

    Tag DEEPSLATE_ORE_REPLACEABLES = BlockTag.get("minecraft:deepslate_ore_replaceables");

    Tag IRON_ORES = BlockTag.get("minecraft:iron_ores");

    Tag WOODEN_PRESSURE_PLATES = BlockTag.get("minecraft:wooden_pressure_plates");

    Tag COAL_ORES = BlockTag.get("minecraft:coal_ores");

    Tag STAIRS = BlockTag.get("minecraft:stairs");

    Tag COMPLETES_FIND_TREE_TUTORIAL = BlockTag.get("minecraft:completes_find_tree_tutorial");

    Tag CANDLES = BlockTag.get("minecraft:candles");

    Tag GOATS_SPAWNABLE_ON = BlockTag.get("minecraft:goats_spawnable_on");

    Tag BASE_STONE_OVERWORLD = BlockTag.get("minecraft:base_stone_overworld");

    Tag BEEHIVES = BlockTag.get("minecraft:beehives");

    Tag CAMEL_SAND_STEP_SOUND_BLOCKS = BlockTag.get("minecraft:camel_sand_step_sound_blocks");

    Tag TRAIL_RUINS_REPLACEABLE = BlockTag.get("minecraft:trail_ruins_replaceable");

    Tag MOSS_REPLACEABLE = BlockTag.get("minecraft:moss_replaceable");

    Tag WALL_POST_OVERRIDE = BlockTag.get("minecraft:wall_post_override");

    Tag WALLS = BlockTag.get("minecraft:walls");

    Tag WALL_SIGNS = BlockTag.get("minecraft:wall_signs");

    Tag UNDERWATER_BONEMEALS = BlockTag.get("minecraft:underwater_bonemeals");

    Tag REPLACEABLE = BlockTag.get("minecraft:replaceable");

    Tag STANDING_SIGNS = BlockTag.get("minecraft:standing_signs");

    Tag GOLD_ORES = BlockTag.get("minecraft:gold_ores");

    Tag NYLIUM = BlockTag.get("minecraft:nylium");

    Tag MAINTAINS_FARMLAND = BlockTag.get("minecraft:maintains_farmland");

    Tag DIAMOND_ORES = BlockTag.get("minecraft:diamond_ores");

    Tag NEEDS_IRON_TOOL = BlockTag.get("minecraft:needs_iron_tool");

    Tag WITHER_IMMUNE = BlockTag.get("minecraft:wither_immune");

    Tag CANDLE_CAKES = BlockTag.get("minecraft:candle_cakes");

    Tag PIGLIN_REPELLENTS = BlockTag.get("minecraft:piglin_repellents");

    Tag BIRCH_LOGS = BlockTag.get("minecraft:birch_logs");

    Tag CORAL_PLANTS = BlockTag.get("minecraft:coral_plants");

    Tag MANGROVE_ROOTS_CAN_GROW_THROUGH = BlockTag.get("minecraft:mangrove_roots_can_grow_through");

    Tag ENCHANTMENT_POWER_PROVIDER = BlockTag.get("minecraft:enchantment_power_provider");

    Tag ANVIL = BlockTag.get("minecraft:anvil");

    Tag EMERALD_ORES = BlockTag.get("minecraft:emerald_ores");

    Tag ENCHANTMENT_POWER_TRANSMITTER = BlockTag.get("minecraft:enchantment_power_transmitter");

    Tag FALL_DAMAGE_RESETTING = BlockTag.get("minecraft:fall_damage_resetting");

    Tag FROG_PREFER_JUMP_TO = BlockTag.get("minecraft:frog_prefer_jump_to");

    Tag SOUL_SPEED_BLOCKS = BlockTag.get("minecraft:soul_speed_blocks");

    Tag WOODEN_TRAPDOORS = BlockTag.get("minecraft:wooden_trapdoors");

    Tag DRAGON_IMMUNE = BlockTag.get("minecraft:dragon_immune");

    Tag WOODEN_STAIRS = BlockTag.get("minecraft:wooden_stairs");

    Tag WOOL_CARPETS = BlockTag.get("minecraft:wool_carpets");

    Tag ALL_SIGNS = BlockTag.get("minecraft:all_signs");

    Tag GUARDED_BY_PIGLINS = BlockTag.get("minecraft:guarded_by_piglins");

    Tag GEODE_INVALID_BLOCKS = BlockTag.get("minecraft:geode_invalid_blocks");

    Tag BEE_GROWABLES = BlockTag.get("minecraft:bee_growables");

    Tag WOODEN_DOORS = BlockTag.get("minecraft:wooden_doors");

    Tag BEACON_BASE_BLOCKS = BlockTag.get("minecraft:beacon_base_blocks");

    Tag FLOWERS = BlockTag.get("minecraft:flowers");

    Tag SNOW_LAYER_CAN_SURVIVE_ON = BlockTag.get("minecraft:snow_layer_can_survive_on");

    Tag JUNGLE_LOGS = BlockTag.get("minecraft:jungle_logs");

    Tag BAMBOO_BLOCKS = BlockTag.get("minecraft:bamboo_blocks");

    Tag INSIDE_STEP_SOUND_BLOCKS = BlockTag.get("minecraft:inside_step_sound_blocks");

    Tag WART_BLOCKS = BlockTag.get("minecraft:wart_blocks");

    Tag COMBINATION_STEP_SOUND_BLOCKS = BlockTag.get("minecraft:combination_step_sound_blocks");

    Tag STONE_BRICKS = BlockTag.get("minecraft:stone_bricks");

    Tag INVALID_SPAWN_INSIDE = BlockTag.get("minecraft:invalid_spawn_inside");

    Tag INFINIBURN_END = BlockTag.get("minecraft:infiniburn_end");

    Tag DIRT = BlockTag.get("minecraft:dirt");

    Tag MANGROVE_LOGS = BlockTag.get("minecraft:mangrove_logs");

    Tag FEATURES_CANNOT_REPLACE = BlockTag.get("minecraft:features_cannot_replace");

    Tag CROPS = BlockTag.get("minecraft:crops");

    Tag TRAPDOORS = BlockTag.get("minecraft:trapdoors");

    Tag TERRACOTTA = BlockTag.get("minecraft:terracotta");

    Tag SWORD_EFFICIENT = BlockTag.get("minecraft:sword_efficient");

    Tag INFINIBURN_NETHER = BlockTag.get("minecraft:infiniburn_nether");

    Tag AXOLOTLS_SPAWNABLE_ON = BlockTag.get("minecraft:axolotls_spawnable_on");

    Tag CAULDRONS = BlockTag.get("minecraft:cauldrons");

    Tag ALL_HANGING_SIGNS = BlockTag.get("minecraft:all_hanging_signs");

    Tag FOXES_SPAWNABLE_ON = BlockTag.get("minecraft:foxes_spawnable_on");

    Tag CLIMBABLE = BlockTag.get("minecraft:climbable");

    Tag ACACIA_LOGS = BlockTag.get("minecraft:acacia_logs");

    Tag BEDS = BlockTag.get("minecraft:beds");

    Tag ICE = BlockTag.get("minecraft:ice");

    Tag WITHER_SUMMON_BASE_BLOCKS = BlockTag.get("minecraft:wither_summon_base_blocks");

    Tag TALL_FLOWERS = BlockTag.get("minecraft:tall_flowers");

    Tag POLAR_BEARS_SPAWNABLE_ON_ALTERNATE = BlockTag.get("minecraft:polar_bears_spawnable_on_alternate");

    Tag SMALL_FLOWERS = BlockTag.get("minecraft:small_flowers");

    Tag SMELTS_TO_GLASS = BlockTag.get("minecraft:smelts_to_glass");

    Tag DRIPSTONE_REPLACEABLE_BLOCKS = BlockTag.get("minecraft:dripstone_replaceable_blocks");

    Tag REDSTONE_ORES = BlockTag.get("minecraft:redstone_ores");

    Tag WALL_CORALS = BlockTag.get("minecraft:wall_corals");

    Tag FLOWER_POTS = BlockTag.get("minecraft:flower_pots");

    Tag WOODEN_FENCES = BlockTag.get("minecraft:wooden_fences");

    Tag WOLVES_SPAWNABLE_ON = BlockTag.get("minecraft:wolves_spawnable_on");

    Tag FENCES = BlockTag.get("minecraft:fences");

    Tag OAK_LOGS = BlockTag.get("minecraft:oak_logs");

    Tag ENDERMAN_HOLDABLE = BlockTag.get("minecraft:enderman_holdable");

    Tag SNOW_LAYER_CANNOT_SURVIVE_ON = BlockTag.get("minecraft:snow_layer_cannot_survive_on");

    Tag WOODEN_BUTTONS = BlockTag.get("minecraft:wooden_buttons");

    Tag STONE_PRESSURE_PLATES = BlockTag.get("minecraft:stone_pressure_plates");

    Tag SMALL_DRIPLEAF_PLACEABLE = BlockTag.get("minecraft:small_dripleaf_placeable");

    Tag OCCLUDES_VIBRATION_SIGNALS = BlockTag.get("minecraft:occludes_vibration_signals");

    Tag WARPED_STEMS = BlockTag.get("minecraft:warped_stems");

    Tag IMPERMEABLE = BlockTag.get("minecraft:impermeable");

    Tag HOGLIN_REPELLENTS = BlockTag.get("minecraft:hoglin_repellents");

    Tag PREVENT_MOB_SPAWNING_INSIDE = BlockTag.get("minecraft:prevent_mob_spawning_inside");

    Tag SNIFFER_EGG_HATCH_BOOST = BlockTag.get("minecraft:sniffer_egg_hatch_boost");

    Tag LEAVES = BlockTag.get("minecraft:leaves");

    Tag PORTALS = BlockTag.get("minecraft:portals");

    Tag LOGS = BlockTag.get("minecraft:logs");

    Tag CONVERTABLE_TO_MUD = BlockTag.get("minecraft:convertable_to_mud");

    Tag SIGNS = BlockTag.get("minecraft:signs");

    Tag MANGROVE_LOGS_CAN_GROW_THROUGH = BlockTag.get("minecraft:mangrove_logs_can_grow_through");

    Tag OVERWORLD_CARVER_REPLACEABLES = BlockTag.get("minecraft:overworld_carver_replaceables");

    Tag AZALEA_GROWS_ON = BlockTag.get("minecraft:azalea_grows_on");

    Tag FENCE_GATES = BlockTag.get("minecraft:fence_gates");

    Tag PARROTS_SPAWNABLE_ON = BlockTag.get("minecraft:parrots_spawnable_on");

    Tag INFINIBURN_OVERWORLD = BlockTag.get("minecraft:infiniburn_overworld");

    Tag WOOL = BlockTag.get("minecraft:wool");

    Tag AZALEA_ROOT_REPLACEABLE = BlockTag.get("minecraft:azalea_root_replaceable");

    Tag ANCIENT_CITY_REPLACEABLE = BlockTag.get("minecraft:ancient_city_replaceable");

    Tag SAPLINGS = BlockTag.get("minecraft:saplings");

    Tag ANIMALS_SPAWNABLE_ON = BlockTag.get("minecraft:animals_spawnable_on");

    Tag PRESSURE_PLATES = BlockTag.get("minecraft:pressure_plates");

    Tag SCULK_REPLACEABLE = BlockTag.get("minecraft:sculk_replaceable");

    Tag BAMBOO_PLANTABLE_ON = BlockTag.get("minecraft:bamboo_plantable_on");

    Tag SCULK_REPLACEABLE_WORLD_GEN = BlockTag.get("minecraft:sculk_replaceable_world_gen");

    Tag STONE_BUTTONS = BlockTag.get("minecraft:stone_buttons");

    Tag SAND = BlockTag.get("minecraft:sand");

    Tag MUSHROOM_GROW_BLOCK = BlockTag.get("minecraft:mushroom_grow_block");

    Tag UNSTABLE_BOTTOM_CENTER = BlockTag.get("minecraft:unstable_bottom_center");

    Tag VIBRATION_RESONATORS = BlockTag.get("minecraft:vibration_resonators");

    Tag SHULKER_BOXES = BlockTag.get("minecraft:shulker_boxes");

    Tag CEILING_HANGING_SIGNS = BlockTag.get("minecraft:ceiling_hanging_signs");

    Tag NETHER_CARVER_REPLACEABLES = BlockTag.get("minecraft:nether_carver_replaceables");

    Tag BIG_DRIPLEAF_PLACEABLE = BlockTag.get("minecraft:big_dripleaf_placeable");

    Tag LOGS_THAT_BURN = BlockTag.get("minecraft:logs_that_burn");

    Tag DRAGON_TRANSPARENT = BlockTag.get("minecraft:dragon_transparent");

    Tag DOORS = BlockTag.get("minecraft:doors");

    Tag RAILS = BlockTag.get("minecraft:rails");

    Tag BASE_STONE_NETHER = BlockTag.get("minecraft:base_stone_nether");

    Tag STONE_ORE_REPLACEABLES = BlockTag.get("minecraft:stone_ore_replaceables");

    Tag SOUL_FIRE_BASE_BLOCKS = BlockTag.get("minecraft:soul_fire_base_blocks");

    Tag FROGS_SPAWNABLE_ON = BlockTag.get("minecraft:frogs_spawnable_on");

    Tag NEEDS_DIAMOND_TOOL = BlockTag.get("minecraft:needs_diamond_tool");

    Tag OVERWORLD_NATURAL_LOGS = BlockTag.get("minecraft:overworld_natural_logs");

    Tag CAVE_VINES = BlockTag.get("minecraft:cave_vines");

    Tag DARK_OAK_LOGS = BlockTag.get("minecraft:dark_oak_logs");

    Tag MOOSHROOMS_SPAWNABLE_ON = BlockTag.get("minecraft:mooshrooms_spawnable_on");

    Tag SNAPS_GOAT_HORN = BlockTag.get("minecraft:snaps_goat_horn");

    Tag CRIMSON_STEMS = BlockTag.get("minecraft:crimson_stems");

    Tag CORAL_BLOCKS = BlockTag.get("minecraft:coral_blocks");

    Tag NEEDS_STONE_TOOL = BlockTag.get("minecraft:needs_stone_tool");

    Tag LAPIS_ORES = BlockTag.get("minecraft:lapis_ores");

    Tag SNIFFER_DIGGABLE_BLOCK = BlockTag.get("minecraft:sniffer_diggable_block");

    Tag BANNERS = BlockTag.get("minecraft:banners");

    Tag VALID_SPAWN = BlockTag.get("minecraft:valid_spawn");

    Tag STRIDER_WARM_BLOCKS = BlockTag.get("minecraft:strider_warm_blocks");
}
