package net.minestom.server.gametag;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface EntityTags {
    Tag FALL_DAMAGE_IMMUNE = EntityTag.get("minecraft:fall_damage_immune");

    Tag RAIDERS = EntityTag.get("minecraft:raiders");

    Tag NON_CONTROLLING_RIDER = EntityTag.get("minecraft:non_controlling_rider");

    Tag AXOLOTL_ALWAYS_HOSTILES = EntityTag.get("minecraft:axolotl_always_hostiles");

    Tag SKELETONS = EntityTag.get("minecraft:skeletons");

    Tag ARROWS = EntityTag.get("minecraft:arrows");

    Tag CAN_BREATHE_UNDER_WATER = EntityTag.get("minecraft:can_breathe_under_water");

    Tag FROG_FOOD = EntityTag.get("minecraft:frog_food");

    Tag FREEZE_HURTS_EXTRA_TYPES = EntityTag.get("minecraft:freeze_hurts_extra_types");

    Tag FREEZE_IMMUNE_ENTITY_TYPES = EntityTag.get("minecraft:freeze_immune_entity_types");

    Tag UNDEAD = EntityTag.get("minecraft:undead");

    Tag IMPACT_PROJECTILES = EntityTag.get("minecraft:impact_projectiles");

    Tag ZOMBIES = EntityTag.get("minecraft:zombies");

    Tag DISMOUNTS_UNDERWATER = EntityTag.get("minecraft:dismounts_underwater");

    Tag AXOLOTL_HUNT_TARGETS = EntityTag.get("minecraft:axolotl_hunt_targets");

    Tag POWDER_SNOW_WALKABLE_MOBS = EntityTag.get("minecraft:powder_snow_walkable_mobs");

    Tag BEEHIVE_INHABITORS = EntityTag.get("minecraft:beehive_inhabitors");
}
