package net.minestom.server.gametag;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface FluidTags {
    Tag LAVA = FluidTag.get("minecraft:lava");

    Tag WATER = FluidTag.get("minecraft:water");
}
