package net.minestom.server.gametag;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface GameEventTags {
    Tag WARDEN_CAN_LISTEN = GameEventTag.get("minecraft:warden_can_listen");

    Tag SHRIEKER_CAN_LISTEN = GameEventTag.get("minecraft:shrieker_can_listen");

    Tag ALLAY_CAN_LISTEN = GameEventTag.get("minecraft:allay_can_listen");

    Tag VIBRATIONS = GameEventTag.get("minecraft:vibrations");

    Tag IGNORE_VIBRATIONS_SNEAKING = GameEventTag.get("minecraft:ignore_vibrations_sneaking");
}
