package net.minestom.server.gametag;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface ItemTags {
    Tag CHERRY_LOGS = ItemTag.get("minecraft:cherry_logs");

    Tag WOODEN_SLABS = ItemTag.get("minecraft:wooden_slabs");

    Tag SWORDS = ItemTag.get("minecraft:swords");

    Tag PLANKS = ItemTag.get("minecraft:planks");

    Tag BUTTONS = ItemTag.get("minecraft:buttons");

    Tag LECTERN_BOOKS = ItemTag.get("minecraft:lectern_books");

    Tag SLABS = ItemTag.get("minecraft:slabs");

    Tag SPRUCE_LOGS = ItemTag.get("minecraft:spruce_logs");

    Tag FREEZE_IMMUNE_WEARABLES = ItemTag.get("minecraft:freeze_immune_wearables");

    Tag COPPER_ORES = ItemTag.get("minecraft:copper_ores");

    Tag DAMPENS_VIBRATIONS = ItemTag.get("minecraft:dampens_vibrations");

    Tag CHEST_BOATS = ItemTag.get("minecraft:chest_boats");

    Tag CLUSTER_MAX_HARVESTABLES = ItemTag.get("minecraft:cluster_max_harvestables");

    Tag IRON_ORES = ItemTag.get("minecraft:iron_ores");

    Tag WOODEN_PRESSURE_PLATES = ItemTag.get("minecraft:wooden_pressure_plates");

    Tag STONE_TOOL_MATERIALS = ItemTag.get("minecraft:stone_tool_materials");

    Tag COAL_ORES = ItemTag.get("minecraft:coal_ores");

    Tag SNIFFER_FOOD = ItemTag.get("minecraft:sniffer_food");

    Tag ARROWS = ItemTag.get("minecraft:arrows");

    Tag STONE_CRAFTING_MATERIALS = ItemTag.get("minecraft:stone_crafting_materials");

    Tag STAIRS = ItemTag.get("minecraft:stairs");

    Tag COMPLETES_FIND_TREE_TUTORIAL = ItemTag.get("minecraft:completes_find_tree_tutorial");

    Tag CANDLES = ItemTag.get("minecraft:candles");

    Tag DECORATED_POT_SHERDS = ItemTag.get("minecraft:decorated_pot_sherds");

    Tag WALLS = ItemTag.get("minecraft:walls");

    Tag COMPASSES = ItemTag.get("minecraft:compasses");

    Tag AXES = ItemTag.get("minecraft:axes");

    Tag GOLD_ORES = ItemTag.get("minecraft:gold_ores");

    Tag DIAMOND_ORES = ItemTag.get("minecraft:diamond_ores");

    Tag BEACON_PAYMENT_ITEMS = ItemTag.get("minecraft:beacon_payment_items");

    Tag PIGLIN_REPELLENTS = ItemTag.get("minecraft:piglin_repellents");

    Tag BIRCH_LOGS = ItemTag.get("minecraft:birch_logs");

    Tag BOOKSHELF_BOOKS = ItemTag.get("minecraft:bookshelf_books");

    Tag ANVIL = ItemTag.get("minecraft:anvil");

    Tag EMERALD_ORES = ItemTag.get("minecraft:emerald_ores");

    Tag WOODEN_TRAPDOORS = ItemTag.get("minecraft:wooden_trapdoors");

    Tag WOODEN_STAIRS = ItemTag.get("minecraft:wooden_stairs");

    Tag WOOL_CARPETS = ItemTag.get("minecraft:wool_carpets");

    Tag BOATS = ItemTag.get("minecraft:boats");

    Tag WOODEN_DOORS = ItemTag.get("minecraft:wooden_doors");

    Tag TRIM_MATERIALS = ItemTag.get("minecraft:trim_materials");

    Tag FLOWERS = ItemTag.get("minecraft:flowers");

    Tag JUNGLE_LOGS = ItemTag.get("minecraft:jungle_logs");

    Tag BAMBOO_BLOCKS = ItemTag.get("minecraft:bamboo_blocks");

    Tag WART_BLOCKS = ItemTag.get("minecraft:wart_blocks");

    Tag STONE_BRICKS = ItemTag.get("minecraft:stone_bricks");

    Tag IGNORED_BY_PIGLIN_BABIES = ItemTag.get("minecraft:ignored_by_piglin_babies");

    Tag DIRT = ItemTag.get("minecraft:dirt");

    Tag MANGROVE_LOGS = ItemTag.get("minecraft:mangrove_logs");

    Tag TRAPDOORS = ItemTag.get("minecraft:trapdoors");

    Tag TERRACOTTA = ItemTag.get("minecraft:terracotta");

    Tag TRIMMABLE_ARMOR = ItemTag.get("minecraft:trimmable_armor");

    Tag ACACIA_LOGS = ItemTag.get("minecraft:acacia_logs");

    Tag PICKAXES = ItemTag.get("minecraft:pickaxes");

    Tag NOTEBLOCK_TOP_INSTRUMENTS = ItemTag.get("minecraft:noteblock_top_instruments");

    Tag BEDS = ItemTag.get("minecraft:beds");

    Tag CREEPER_DROP_MUSIC_DISCS = ItemTag.get("minecraft:creeper_drop_music_discs");

    Tag TALL_FLOWERS = ItemTag.get("minecraft:tall_flowers");

    Tag SMALL_FLOWERS = ItemTag.get("minecraft:small_flowers");

    Tag BREAKS_DECORATED_POTS = ItemTag.get("minecraft:breaks_decorated_pots");

    Tag SMELTS_TO_GLASS = ItemTag.get("minecraft:smelts_to_glass");

    Tag TOOLS = ItemTag.get("minecraft:tools");

    Tag REDSTONE_ORES = ItemTag.get("minecraft:redstone_ores");

    Tag WOODEN_FENCES = ItemTag.get("minecraft:wooden_fences");

    Tag FENCES = ItemTag.get("minecraft:fences");

    Tag VILLAGER_PLANTABLE_SEEDS = ItemTag.get("minecraft:villager_plantable_seeds");

    Tag OAK_LOGS = ItemTag.get("minecraft:oak_logs");

    Tag PIGLIN_FOOD = ItemTag.get("minecraft:piglin_food");

    Tag MUSIC_DISCS = ItemTag.get("minecraft:music_discs");

    Tag PIGLIN_LOVED = ItemTag.get("minecraft:piglin_loved");

    Tag WOODEN_BUTTONS = ItemTag.get("minecraft:wooden_buttons");

    Tag WARPED_STEMS = ItemTag.get("minecraft:warped_stems");

    Tag HANGING_SIGNS = ItemTag.get("minecraft:hanging_signs");

    Tag LEAVES = ItemTag.get("minecraft:leaves");

    Tag NON_FLAMMABLE_WOOD = ItemTag.get("minecraft:non_flammable_wood");

    Tag LOGS = ItemTag.get("minecraft:logs");

    Tag SIGNS = ItemTag.get("minecraft:signs");

    Tag FOX_FOOD = ItemTag.get("minecraft:fox_food");

    Tag FISHES = ItemTag.get("minecraft:fishes");

    Tag FENCE_GATES = ItemTag.get("minecraft:fence_gates");

    Tag SHOVELS = ItemTag.get("minecraft:shovels");

    Tag WOOL = ItemTag.get("minecraft:wool");

    Tag SAPLINGS = ItemTag.get("minecraft:saplings");

    Tag CREEPER_IGNITERS = ItemTag.get("minecraft:creeper_igniters");

    Tag STONE_BUTTONS = ItemTag.get("minecraft:stone_buttons");

    Tag SAND = ItemTag.get("minecraft:sand");

    Tag HOES = ItemTag.get("minecraft:hoes");

    Tag LOGS_THAT_BURN = ItemTag.get("minecraft:logs_that_burn");

    Tag DOORS = ItemTag.get("minecraft:doors");

    Tag RAILS = ItemTag.get("minecraft:rails");

    Tag SOUL_FIRE_BASE_BLOCKS = ItemTag.get("minecraft:soul_fire_base_blocks");

    Tag DECORATED_POT_INGREDIENTS = ItemTag.get("minecraft:decorated_pot_ingredients");

    Tag DARK_OAK_LOGS = ItemTag.get("minecraft:dark_oak_logs");

    Tag AXOLOTL_TEMPT_ITEMS = ItemTag.get("minecraft:axolotl_tempt_items");

    Tag CRIMSON_STEMS = ItemTag.get("minecraft:crimson_stems");

    Tag LAPIS_ORES = ItemTag.get("minecraft:lapis_ores");

    Tag BANNERS = ItemTag.get("minecraft:banners");

    Tag TRIM_TEMPLATES = ItemTag.get("minecraft:trim_templates");

    Tag COALS = ItemTag.get("minecraft:coals");
}
