package net.minestom.server.item.armor;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface TrimPatterns {
    Key TIDE = Key.key("minecraft:tide");

    Key RIB = Key.key("minecraft:rib");

    Key BOLT = Key.key("minecraft:bolt");

    Key HOST = Key.key("minecraft:host");

    Key SILENCE = Key.key("minecraft:silence");

    Key WILD = Key.key("minecraft:wild");

    Key WAYFINDER = Key.key("minecraft:wayfinder");

    Key FLOW = Key.key("minecraft:flow");

    Key DUNE = Key.key("minecraft:dune");

    Key RAISER = Key.key("minecraft:raiser");

    Key SNOUT = Key.key("minecraft:snout");

    Key VEX = Key.key("minecraft:vex");

    Key SPIRE = Key.key("minecraft:spire");

    Key SENTRY = Key.key("minecraft:sentry");

    Key EYE = Key.key("minecraft:eye");

    Key WARD = Key.key("minecraft:ward");

    Key COAST = Key.key("minecraft:coast");

    Key SHAPER = Key.key("minecraft:shaper");
}
