package net.minestom.server.item.armor;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface TrimMaterials {
    Key LAPIS = Key.key("minecraft:lapis");

    Key IRON = Key.key("minecraft:iron");

    Key DIAMOND = Key.key("minecraft:diamond");

    Key AMETHYST = Key.key("minecraft:amethyst");

    Key COPPER = Key.key("minecraft:copper");

    Key QUARTZ = Key.key("minecraft:quartz");

    Key EMERALD = Key.key("minecraft:emerald");

    Key REDSTONE = Key.key("minecraft:redstone");

    Key GOLD = Key.key("minecraft:gold");

    Key NETHERITE = Key.key("minecraft:netherite");
}
