package net.minestom.server.entity.damage;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface DamageTypes {
    Key WITHER = Key.key("minecraft:wither");

    Key SONIC_BOOM = Key.key("minecraft:sonic_boom");

    Key WITHER_SKULL = Key.key("minecraft:wither_skull");

    Key DRY_OUT = Key.key("minecraft:dry_out");

    Key TRIDENT = Key.key("minecraft:trident");

    Key ON_FIRE = Key.key("minecraft:on_fire");

    Key FALL = Key.key("minecraft:fall");

    Key MOB_ATTACK = Key.key("minecraft:mob_attack");

    Key MOB_PROJECTILE = Key.key("minecraft:mob_projectile");

    Key CAMPFIRE = Key.key("minecraft:campfire");

    Key THROWN = Key.key("minecraft:thrown");

    Key FALLING_STALACTITE = Key.key("minecraft:falling_stalactite");

    Key FIREBALL = Key.key("minecraft:fireball");

    Key FALLING_BLOCK = Key.key("minecraft:falling_block");

    Key WIND_CHARGE = Key.key("minecraft:wind_charge");

    Key PLAYER_EXPLOSION = Key.key("minecraft:player_explosion");

    Key SPIT = Key.key("minecraft:spit");

    Key STING = Key.key("minecraft:sting");

    Key UNATTRIBUTED_FIREBALL = Key.key("minecraft:unattributed_fireball");

    Key IN_WALL = Key.key("minecraft:in_wall");

    Key IN_FIRE = Key.key("minecraft:in_fire");

    Key ARROW = Key.key("minecraft:arrow");

    Key HOT_FLOOR = Key.key("minecraft:hot_floor");

    Key DROWN = Key.key("minecraft:drown");

    Key STARVE = Key.key("minecraft:starve");

    Key GENERIC_KILL = Key.key("minecraft:generic_kill");

    Key DRAGON_BREATH = Key.key("minecraft:dragon_breath");

    Key MOB_ATTACK_NO_AGGRO = Key.key("minecraft:mob_attack_no_aggro");

    Key LAVA = Key.key("minecraft:lava");

    Key OUTSIDE_BORDER = Key.key("minecraft:outside_border");

    Key FLY_INTO_WALL = Key.key("minecraft:fly_into_wall");

    Key LIGHTNING_BOLT = Key.key("minecraft:lightning_bolt");

    Key PLAYER_ATTACK = Key.key("minecraft:player_attack");

    Key FREEZE = Key.key("minecraft:freeze");

    Key FALLING_ANVIL = Key.key("minecraft:falling_anvil");

    Key OUT_OF_WORLD = Key.key("minecraft:out_of_world");

    Key MAGIC = Key.key("minecraft:magic");

    Key SWEET_BERRY_BUSH = Key.key("minecraft:sweet_berry_bush");

    Key FIREWORKS = Key.key("minecraft:fireworks");

    Key EXPLOSION = Key.key("minecraft:explosion");

    Key BAD_RESPAWN_POINT = Key.key("minecraft:bad_respawn_point");

    Key STALAGMITE = Key.key("minecraft:stalagmite");

    Key THORNS = Key.key("minecraft:thorns");

    Key INDIRECT_MAGIC = Key.key("minecraft:indirect_magic");

    Key CRAMMING = Key.key("minecraft:cramming");

    Key CACTUS = Key.key("minecraft:cactus");

    Key GENERIC = Key.key("minecraft:generic");
}
