package net.minestom.server.entity.metadata.other;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface PaintingVariants {
    Key BOUQUET = Key.key("minecraft:bouquet");

    Key WITHER = Key.key("minecraft:wither");

    Key ALBAN = Key.key("minecraft:alban");

    Key UNPACKED = Key.key("minecraft:unpacked");

    Key AZTEC = Key.key("minecraft:aztec");

    Key MATCH = Key.key("minecraft:match");

    Key FINDING = Key.key("minecraft:finding");

    Key BAROQUE = Key.key("minecraft:baroque");

    Key ENDBOSS = Key.key("minecraft:endboss");

    Key ORB = Key.key("minecraft:orb");

    Key AZTEC2 = Key.key("minecraft:aztec2");

    Key SUNFLOWERS = Key.key("minecraft:sunflowers");

    Key CHANGING = Key.key("minecraft:changing");

    Key WASTELAND = Key.key("minecraft:wasteland");

    Key DONKEY_KONG = Key.key("minecraft:donkey_kong");

    Key BUST = Key.key("minecraft:bust");

    Key POOL = Key.key("minecraft:pool");

    Key PIGSCENE = Key.key("minecraft:pigscene");

    Key BURNING_SKULL = Key.key("minecraft:burning_skull");

    Key FIRE = Key.key("minecraft:fire");

    Key SEA = Key.key("minecraft:sea");

    Key SUNSET = Key.key("minecraft:sunset");

    Key POND = Key.key("minecraft:pond");

    Key HUMBLE = Key.key("minecraft:humble");

    Key TIDES = Key.key("minecraft:tides");

    Key PRAIRIE_RIDE = Key.key("minecraft:prairie_ride");

    Key FERN = Key.key("minecraft:fern");

    Key PASSAGE = Key.key("minecraft:passage");

    Key LOWMIST = Key.key("minecraft:lowmist");

    Key COURBET = Key.key("minecraft:courbet");

    Key WANDERER = Key.key("minecraft:wanderer");

    Key BACKYARD = Key.key("minecraft:backyard");

    Key EARTH = Key.key("minecraft:earth");

    Key SKULL_AND_ROSES = Key.key("minecraft:skull_and_roses");

    Key CAVEBIRD = Key.key("minecraft:cavebird");

    Key FIGHTERS = Key.key("minecraft:fighters");

    Key COTAN = Key.key("minecraft:cotan");

    Key CREEBET = Key.key("minecraft:creebet");

    Key OWLEMONS = Key.key("minecraft:owlemons");

    Key GRAHAM = Key.key("minecraft:graham");

    Key MEDITATIVE = Key.key("minecraft:meditative");

    Key KEBAB = Key.key("minecraft:kebab");

    Key STAGE = Key.key("minecraft:stage");

    Key BOMB = Key.key("minecraft:bomb");

    Key PLANT = Key.key("minecraft:plant");

    Key WATER = Key.key("minecraft:water");

    Key POINTER = Key.key("minecraft:pointer");

    Key SKELETON = Key.key("minecraft:skeleton");

    Key VOID = Key.key("minecraft:void");

    Key WIND = Key.key("minecraft:wind");
}
