package net.minestom.server.instance.block.jukebox;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface JukeboxSongs {
    Key PRECIPICE = Key.key("minecraft:precipice");

    Key STAL = Key.key("minecraft:stal");

    Key STRAD = Key.key("minecraft:strad");

    Key CREATOR_MUSIC_BOX = Key.key("minecraft:creator_music_box");

    Key _13 = Key.key("minecraft:13");

    Key RELIC = Key.key("minecraft:relic");

    Key FAR = Key.key("minecraft:far");

    Key BLOCKS = Key.key("minecraft:blocks");

    Key _5 = Key.key("minecraft:5");

    Key OTHERSIDE = Key.key("minecraft:otherside");

    Key MELLOHI = Key.key("minecraft:mellohi");

    Key MALL = Key.key("minecraft:mall");

    Key CHIRP = Key.key("minecraft:chirp");

    Key CREATOR = Key.key("minecraft:creator");

    Key PIGSTEP = Key.key("minecraft:pigstep");

    Key WARD = Key.key("minecraft:ward");

    Key CAT = Key.key("minecraft:cat");

    Key WAIT = Key.key("minecraft:wait");

    Key _11 = Key.key("minecraft:11");
}
