package net.minestom.server.world;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface DimensionTypes {
    Key THE_END = Key.key("minecraft:the_end");

    Key OVERWORLD_CAVES = Key.key("minecraft:overworld_caves");

    Key THE_NETHER = Key.key("minecraft:the_nether");

    Key OVERWORLD = Key.key("minecraft:overworld");
}
