package net.minestom.server.instance.block.banner;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface BannerPatterns {
    Key BORDER = Key.key("minecraft:border");

    Key SQUARE_BOTTOM_RIGHT = Key.key("minecraft:square_bottom_right");

    Key STRIPE_RIGHT = Key.key("minecraft:stripe_right");

    Key FLOW = Key.key("minecraft:flow");

    Key RHOMBUS = Key.key("minecraft:rhombus");

    Key TRIANGLES_TOP = Key.key("minecraft:triangles_top");

    Key GRADIENT = Key.key("minecraft:gradient");

    Key GLOBE = Key.key("minecraft:globe");

    Key MOJANG = Key.key("minecraft:mojang");

    Key STRIPE_BOTTOM = Key.key("minecraft:stripe_bottom");

    Key STRIPE_MIDDLE = Key.key("minecraft:stripe_middle");

    Key FLOWER = Key.key("minecraft:flower");

    Key DIAGONAL_UP_RIGHT = Key.key("minecraft:diagonal_up_right");

    Key CIRCLE = Key.key("minecraft:circle");

    Key HALF_HORIZONTAL = Key.key("minecraft:half_horizontal");

    Key BRICKS = Key.key("minecraft:bricks");

    Key TRIANGLE_BOTTOM = Key.key("minecraft:triangle_bottom");

    Key CURLY_BORDER = Key.key("minecraft:curly_border");

    Key BASE = Key.key("minecraft:base");

    Key PIGLIN = Key.key("minecraft:piglin");

    Key STRIPE_CENTER = Key.key("minecraft:stripe_center");

    Key SQUARE_BOTTOM_LEFT = Key.key("minecraft:square_bottom_left");

    Key SQUARE_TOP_RIGHT = Key.key("minecraft:square_top_right");

    Key STRIPE_DOWNRIGHT = Key.key("minecraft:stripe_downright");

    Key GUSTER = Key.key("minecraft:guster");

    Key GRADIENT_UP = Key.key("minecraft:gradient_up");

    Key DIAGONAL_RIGHT = Key.key("minecraft:diagonal_right");

    Key HALF_VERTICAL_RIGHT = Key.key("minecraft:half_vertical_right");

    Key SMALL_STRIPES = Key.key("minecraft:small_stripes");

    Key CROSS = Key.key("minecraft:cross");

    Key DIAGONAL_LEFT = Key.key("minecraft:diagonal_left");

    Key SKULL = Key.key("minecraft:skull");

    Key STRIPE_DOWNLEFT = Key.key("minecraft:stripe_downleft");

    Key DIAGONAL_UP_LEFT = Key.key("minecraft:diagonal_up_left");

    Key HALF_VERTICAL = Key.key("minecraft:half_vertical");

    Key TRIANGLE_TOP = Key.key("minecraft:triangle_top");

    Key HALF_HORIZONTAL_BOTTOM = Key.key("minecraft:half_horizontal_bottom");

    Key SQUARE_TOP_LEFT = Key.key("minecraft:square_top_left");

    Key STRIPE_TOP = Key.key("minecraft:stripe_top");

    Key CREEPER = Key.key("minecraft:creeper");

    Key STRIPE_LEFT = Key.key("minecraft:stripe_left");

    Key TRIANGLES_BOTTOM = Key.key("minecraft:triangles_bottom");

    Key STRAIGHT_CROSS = Key.key("minecraft:straight_cross");
}
