package net.minestom.server.entity.metadata.animal.tameable;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface WolfVariants {
    Key BLACK = Key.key("minecraft:black");

    Key CHESTNUT = Key.key("minecraft:chestnut");

    Key SNOWY = Key.key("minecraft:snowy");

    Key STRIPED = Key.key("minecraft:striped");

    Key ASHEN = Key.key("minecraft:ashen");

    Key SPOTTED = Key.key("minecraft:spotted");

    Key RUSTY = Key.key("minecraft:rusty");

    Key WOODS = Key.key("minecraft:woods");

    Key PALE = Key.key("minecraft:pale");
}
