package net.minestom.server.world.biome;

import net.kyori.adventure.key.Key;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface Biomes {
    Key SNOWY_SLOPES = Key.key("minecraft:snowy_slopes");

    Key OLD_GROWTH_PINE_TAIGA = Key.key("minecraft:old_growth_pine_taiga");

    Key MUSHROOM_FIELDS = Key.key("minecraft:mushroom_fields");

    Key TAIGA = Key.key("minecraft:taiga");

    Key DEEP_OCEAN = Key.key("minecraft:deep_ocean");

    Key ERODED_BADLANDS = Key.key("minecraft:eroded_badlands");

    Key FROZEN_RIVER = Key.key("minecraft:frozen_river");

    Key END_HIGHLANDS = Key.key("minecraft:end_highlands");

    Key CHERRY_GROVE = Key.key("minecraft:cherry_grove");

    Key SUNFLOWER_PLAINS = Key.key("minecraft:sunflower_plains");

    Key BIRCH_FOREST = Key.key("minecraft:birch_forest");

    Key WINDSWEPT_HILLS = Key.key("minecraft:windswept_hills");

    Key BAMBOO_JUNGLE = Key.key("minecraft:bamboo_jungle");

    Key WOODED_BADLANDS = Key.key("minecraft:wooded_badlands");

    Key BADLANDS = Key.key("minecraft:badlands");

    Key SAVANNA_PLATEAU = Key.key("minecraft:savanna_plateau");

    Key BEACH = Key.key("minecraft:beach");

    Key DARK_FOREST = Key.key("minecraft:dark_forest");

    Key STONY_PEAKS = Key.key("minecraft:stony_peaks");

    Key MANGROVE_SWAMP = Key.key("minecraft:mangrove_swamp");

    Key SPARSE_JUNGLE = Key.key("minecraft:sparse_jungle");

    Key LUKEWARM_OCEAN = Key.key("minecraft:lukewarm_ocean");

    Key RIVER = Key.key("minecraft:river");

    Key STONY_SHORE = Key.key("minecraft:stony_shore");

    Key WARPED_FOREST = Key.key("minecraft:warped_forest");

    Key SNOWY_PLAINS = Key.key("minecraft:snowy_plains");

    Key DRIPSTONE_CAVES = Key.key("minecraft:dripstone_caves");

    Key SNOWY_TAIGA = Key.key("minecraft:snowy_taiga");

    Key GROVE = Key.key("minecraft:grove");

    Key SWAMP = Key.key("minecraft:swamp");

    Key JAGGED_PEAKS = Key.key("minecraft:jagged_peaks");

    Key COLD_OCEAN = Key.key("minecraft:cold_ocean");

    Key FOREST = Key.key("minecraft:forest");

    Key LUSH_CAVES = Key.key("minecraft:lush_caves");

    Key BASALT_DELTAS = Key.key("minecraft:basalt_deltas");

    Key DEEP_COLD_OCEAN = Key.key("minecraft:deep_cold_ocean");

    Key ICE_SPIKES = Key.key("minecraft:ice_spikes");

    Key END_MIDLANDS = Key.key("minecraft:end_midlands");

    Key FROZEN_OCEAN = Key.key("minecraft:frozen_ocean");

    Key DESERT = Key.key("minecraft:desert");

    Key DEEP_FROZEN_OCEAN = Key.key("minecraft:deep_frozen_ocean");

    Key WINDSWEPT_FOREST = Key.key("minecraft:windswept_forest");

    Key JUNGLE = Key.key("minecraft:jungle");

    Key OCEAN = Key.key("minecraft:ocean");

    Key OLD_GROWTH_SPRUCE_TAIGA = Key.key("minecraft:old_growth_spruce_taiga");

    Key SNOWY_BEACH = Key.key("minecraft:snowy_beach");

    Key WINDSWEPT_SAVANNA = Key.key("minecraft:windswept_savanna");

    Key END_BARRENS = Key.key("minecraft:end_barrens");

    Key WARM_OCEAN = Key.key("minecraft:warm_ocean");

    Key DEEP_LUKEWARM_OCEAN = Key.key("minecraft:deep_lukewarm_ocean");

    Key FLOWER_FOREST = Key.key("minecraft:flower_forest");

    Key SOUL_SAND_VALLEY = Key.key("minecraft:soul_sand_valley");

    Key NETHER_WASTES = Key.key("minecraft:nether_wastes");

    Key FROZEN_PEAKS = Key.key("minecraft:frozen_peaks");

    Key THE_END = Key.key("minecraft:the_end");

    Key SMALL_END_ISLANDS = Key.key("minecraft:small_end_islands");

    Key OLD_GROWTH_BIRCH_FOREST = Key.key("minecraft:old_growth_birch_forest");

    Key CRIMSON_FOREST = Key.key("minecraft:crimson_forest");

    Key THE_VOID = Key.key("minecraft:the_void");

    Key DEEP_DARK = Key.key("minecraft:deep_dark");

    Key MEADOW = Key.key("minecraft:meadow");

    Key WINDSWEPT_GRAVELLY_HILLS = Key.key("minecraft:windswept_gravelly_hills");

    Key SAVANNA = Key.key("minecraft:savanna");

    Key PLAINS = Key.key("minecraft:plains");
}
