name: Build and deploy Javadoc

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build javadoc
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew javadoc

      - name: Deploy javadoc to its assigned branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: javadoc
          FOLDER: build/docs/javadoc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}